name: "Publish Docs"

# To run this workflow manually from the Actions tab
on:
  # Auto-trigger this workflow on tag creation
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  RTDS_OCIFS_PROJECT: https://readthedocs.org/api/v3/projects/ocifs
  RTDS_OCIFS_TOKEN: ${{ secrets.RTDS_OCIFS_TOKEN }}

jobs:
  build-n-publish:
    name: Build and publish Docs 📖 to Readthedocs
    runs-on: ubuntu-latest

    steps:
      - name: When tag 🏷️ pushed - Trigger Readthedocs build
        if: github.event_name == 'push' && startsWith(github.ref_name, 'v')
        run: |
          # trigger build/publish of latest version
          curl \
            -X POST \
            -H "Authorization: Token $RTDS_OCIFS_TOKEN" $RTDS_OCIFS_PROJECT/versions/latest/builds/
          # add 15 minutes wait time for readthedocs see freshly created tag
          sleep 15m
          # trigger build/publish of v*.*.* version
          curl \
            -X POST \
            -H "Authorization: Token $RTDS_OCIFS_TOKEN" $RTDS_OCIFS_PROJECT/versions/${{ github.ref_name }}/builds/
